"""add cascade delete on memory_log message_id fk

Revision ID: 0aefaf6cf347
Revises: 0a3f16978bf8
Create Date: 2026-03-24 21:56:10.575366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aefaf6cf347'
down_revision: Union[str, Sequence[str], None] = '0a3f16978bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memory_log_message_id_fkey'), 'memory_log', type_='foreignkey')
    op.create_foreign_key(None, 'memory_log', 'chat_message', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memory_log', type_='foreignkey')
    op.create_foreign_key(op.f('memory_log_message_id_fkey'), 'memory_log', 'chat_message', ['message_id'], ['id'])
    # ### end Alembic commands ###
