"""added created_at and updated_at to user

Revision ID: 1d153d44399c
Revises: a20c5b5473eb
Create Date: 2026-03-07 21:22:57.884703

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d153d44399c"
down_revision: Union[str, Sequence[str], None] = "a20c5b5473eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )

    op.add_column(
        "chat",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "chat", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )

    op.add_column(
        "chat_message",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "chat_message",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("chat", "updated_at")
    op.drop_column("chat", "created_at")
    op.drop_column("chat_message", "updated_at")
    op.drop_column("chat_message", "created_at")
    # ### end Alembic commands ###
