"""memory is required in memory_embeddings

Revision ID: 3a084e1fc3a7
Revises: bc9b0d0e7e9c
Create Date: 2026-04-04 19:53:27.180934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a084e1fc3a7'
down_revision: Union[str, Sequence[str], None] = 'bc9b0d0e7e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory_embedding', 'memory_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory_embedding', 'memory_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
