"""drop fk on a superseded_by

Revision ID: 732253d88d5a
Revises: 0373eaa00528
Create Date: 2026-03-14 05:52:08.977508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732253d88d5a'
down_revision: Union[str, Sequence[str], None] = '0373eaa00528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memory_structured_superseded_by_fkey'), 'memory_structured', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('memory_structured_superseded_by_fkey'), 'memory_structured', 'memory_structured', ['superseded_by'], ['id'])
    # ### end Alembic commands ###
