"""added server_defaults for created_at and updated_at

Revision ID: a20c5b5473eb
Revises: 860d1b9c0fde
Create Date: 2026-03-07 21:09:53.579453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20c5b5473eb'
down_revision: Union[str, Sequence[str], None] = '860d1b9c0fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
