"""Add email and hashed_password to user

Revision ID: d2a19cb12447
Revises: 3a084e1fc3a7
Create Date: 2026-04-04 21:32:47.767618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a19cb12447'
down_revision: Union[str, Sequence[str], None] = '3a084e1fc3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
